language: r

env:
- R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

warnings_are_errors: false

os:
- linux
- osx

r:
- release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - _R_CHECK_LATEX_VIGNETTES=FALSE
    - _R_CHECK_WEAVE_VIGNETTES=FALSE

addons:
  apt:
    packages:
    - libgsl0-dev
    - texlive-latex-extra

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew cask install basictex
    brew install gsl
    sudo tlmgr update --self
    sudo tlmgr install placeins
    sudo tlmgr install threeparttable
    sudo tlmgr install oberdiek
  fi

branches:
  only:
  - master

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - 'export PKGVER=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)'
  - export REL=$(echo $PKGVER | grep -o "\." | grep -c "\.")
  - echo $PKGVER $REL
  - R CMD INSTALL --build FLBEIA_$PKGVER.tar.gz
  - rm FLBEIA_$PKGVER.tar.gz
  - export RELEASE_PKG_FILE=$(ls FLBEIA*gz)
  - echo $RELEASE_PKG_FILE

deploy:
  provider: releases
  api_key:
    secure: a3XKcwe5LFbAMy4oSMCWrbb7kAlSbGtPtSSi6lK2rd22GY38pC7kaCNt8rHVnjzBWrwgAV+hARtMuemiNlUwk6m0uEjCV5WZ2NmIVGPHEvR2mhz5t9/wxIYKGWRfY0+uWxya+wy15p0WZ0xyDC2w73fUJY2vQ1A4zF2yw3HEGiE=
  file: $RELEASE_PKG_FILE
  skip_cleanup: true
  draft: true
  on:
    repo: flr/FLBEIA
    condition: $REL = "2"
