# .travis.yml for R projects.
#
# https://travis-ci.org/flr/FLCore

warnings_are_errors: false

language: r

matrix:
  include:
    - os: linux
      r: release

sudo: false

cache: packages

before_install:
  - sudo apt-get install -y libgsl-dev

r_github_packages: mawp/spict/spict

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
  - gh-pages
  - /.*/
